[package]
name = "BZR-GMB"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.6.3", package = "gtk4", features = ["v4_6"] }
glib = { version = "0.17.10", package = "glib"}

